---
- name: Installs fish
  community.general.homebrew:
    package: fish
    state: present

- name: Finds binary file path
  command: which fish
  changed_when: false
  register: fish_executable_path

- name: "Adds fish to available shells: {{ fish_executable_path.stdout_lines[0] }}"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    search_string: "{{ fish_executable_path.stdout_lines[0] }}"
    line: "{{ fish_executable_path.stdout_lines[0] }}"

- name: "Changes the shell to fish: {{ fish_executable_path.stdout_lines[0] }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ fish_executable_path.stdout_lines[0] }}"
