---
- name: Install NerdFont's cask
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install NerdFont's
  community.general.homebrew:
    name: font-meslo-lg-nerd-font
    state: present
  # Homebrew module considers "Warning: cask is installed already" output as a failed one.
  # Since there is no way to handle this properly I'm gonna "fix" it with "failed_when: false"
  failed_when: false

- name: Install Starship
  community.general.homebrew:
    name: starship
    state: present

- name: Setup Starship for Fish
  ansible.builtin.copy:
    content: |
      if status --is-login
          starship init fish | source
      end
    dest: "{{ starship_file_path }}"
    force: false
