---
- name: "Finds tide file to check if it's installed already: {{ tide_file_path }}"
  ansible.builtin.stat:
    path: "{{ tide_file_path }}"
  register: tideFileStat

- name: "Installs Tide ( https://github.com/IlanCosman/tide ) theme for Fish"
  ansible.builtin.shell:
    cmd: "fisher install IlanCosman/tide@v5"
    executable: "{{ fish_executable }}"
  when: false == tideFileStat.stat.exists

- name: "Config Tide via environment varibles"
  ansible.builtin.shell: # noqa no-changed-when
    cmd: "set --universal {{ item.name | quote }} {{ item.value | quote }}"
    executable: "{{ fish_executable }}"
  loop: "{{ tide_environment_variables }}"
  when: false == tideFileStat.stat.exists
