---
- hosts: localhost
  connection: local
  name: "Install the whole environment for the OSX"
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install utilities
      community.general.homebrew:
        name:
          - ack
          - bat
          - btop
          - exa
          - fd
          - htop
        state: present

    - name: Install Fish and its parts
      ansible.builtin.import_role:
        name: fish
      vars:
        username: "{{ ansible_user_id }}"
