---
- name: "Install the whole environment for the OSX"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install packages
      community.general.homebrew:
        name:
          - ack
          - bat
          - btop
          - eza
          - fd
          - htop
          - zellij
        state: present

    - name: "Copy Wez terminal config"
      ansible.builtin.template:
        src: "./templates/wezterm.lua.j2"
        dest: "~/.config/wezterm/wezterm.lua"
        mode: "0600"
