---
- name: "Install the whole environment for the OSX"
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Install Homebrew taps
      community.general.homebrew_tap:
        state: present
        name:
          - homebrew/cask-fonts
          - sdkman/tap

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: Install packages
      community.general.homebrew:
        name:
          - ack
          - act
          - ansible
          - ansible-lint
          - bat
          - btop
          - dust
          - eza
          - fd
          - gron
          - helm
          - htop
          - jq
          - k9s
          - kind
          - ktlint
          - kubectx
          - midnight-commander
          - ncdu
          - neovim
          - pwgen
          - sdkman-cli
          - tig
          - watch
          - yamllint
          - yq
          - zellij
          - zoxide
          - zsh
          - zsh-history-substring-search
        state: present
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: Install casks
      community.general.homebrew_cask:
        state: present
        name:
          - alt-tab
          - font-fira-code
          - font-hack-nerd-font
          - lulu
          - wezterm
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "~/.nvm/nvm.sh"

    - name: "Copy configs"
      tags: configs
      ansible.builtin.include_role:
        name: cp
      vars:
        cp_entity_source: "{{ item.src }}"
        cp_entity_destination: "{{ item.dest }}"
        cp_entity_name: "{{ item.name }}"
        cp_entity_permissions: "0600"
      loop:
        - {
            name: "Wez terminal config",
            src: "./templates/wezterm.lua.j2",
            dest: "~/.config/wezterm/wezterm.lua",
          }
        - { name: "Zsh config", src: "./templates/zshrc.sh", dest: "~/.zshrc" }
        - {
            name: "Zed config",
            src: "./templates/zed/settings.json",
            dest: "~/.config/zed/settings.json",
          }
        - {
            name: "Zed keymap",
            src: "./templates/zed/keymap.json",
            dest: "~/.config/zed/keymap.json",
          }
