---
- hosts: localhost
  connection: local
  name: "Install the whole environment for the OSX"
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install utilities
      community.general.homebrew:
        name:
          - ack
          - bat
          - btop
          - eza
          - fd
          - htop
          - zellij
        state: present

    - name: Install cask
      community.general.homebrew_cask:
        name:
          - wezterm
        state: present
