---
- name: "Install the whole environment for the OSX"
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Install Homebrew taps
      community.general.homebrew_tap:
        state: present
        name:
          - jesseduffield/lazygit

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install packages
      community.general.homebrew:
        name:
          - ack
          - act
          - ansible
          - ansible-lint
          - bat
          - btop
          - dust
          - eza
          - fd
          - fzf
          - gron
          - helm
          - htop
          - lazygit
          - jq
          - k9s
          - kind
          - ktlint
          - kubectx
          - micro
          - MonitorControl
          - ncdu
          - pwgen
          - ripgrep
          - tig
          - watch
          - yamllint
          - yq
          - zellij
          - zoxide
          - zsh
          - zsh-history-substring-search
        state: latest

    - name: Install casks
      community.general.homebrew_cask:
        state: latest
        name:
          - alt-tab
          - font-fira-code
          - font-hack-nerd-font
          - font-monaspace
          - font-sf-mono
          - keepingyouawake
          - lulu
          - monitorcontrol
          - neovide
          - wezterm

    - name: "Copy configs"
      tags: configs
      ansible.builtin.include_role:
        name: cp
      vars:
        cp_entity_source: "{{ item.src }}"
        cp_entity_destination: "{{ item.dest }}"
        cp_entity_name: "{{ item.name }}"
        cp_entity_permissions: "0600"
      loop:
        - {
            name: "Wez terminal config",
            src: "./templates/wezterm.lua.j2",
            dest: "~/.config/wezterm/wezterm.lua",
          }
        - { name: "Zsh config", src: "./templates/zshrc.sh", dest: "~/.zshrc" }
        - {
            name: "Zed config",
            src: "./templates/zed/settings.json",
            dest: "~/.config/zed/settings.json",
          }
        - {
            name: "Zed keymap",
            src: "./templates/zed/keymap.json",
            dest: "~/.config/zed/keymap.json",
          }
        - { name: "Vim config", src: "./templates/vimrc", dest: "~/.vimrc" }
        - {
            name: "Midnight commander INI config",
            src: "./templates/mc.ini",
            dest: "~/.config/mc/ini",
          }
        - { name: "Kitty config", src: "./templates/kitty.conf", dest: "~/.config/kitty/kitty.conf" }
        - {
            name: "Gemini config",
            src: "./templates/geminiSettings.json",
            dest: "~/.gemini/settings.json",
          }
        - {
            name: "Codex rules: Git",
            src: "./templates/codex/rules/git.rules",
            dest: "~/.codex/rules/git.rules",
          }
        - {
            name: "Codex rules: NPM",
            src: "./templates/codex/rules/npm.rules",
            dest: "~/.codex/rules/npm.rules",
          }
