---
- name: "Install the whole environment for the OSX"
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: Install packages
      community.general.homebrew:
        name:
          - ack
          - act
          - ansible
          - ansible-lint
          - bat
          - btop
          - eza
          - fd
          - gron
          - helm
          - htop
          - jq
          - k9s
          - kind
          - ktlint
          - kubectx
          - midnight-commander
          - ncdu
          - pwgen
          - tig
          - watch
          - yamllint
          - yq
          - zellij
          - zsh
          - zsh-history-substring-search
        state: present
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: Install casks
      community.general.homebrew_cask:
        state: present
        name:
          - alt-tab
          - wezterm
          - font-fira-code
      when: dont_run_homebrew_tasks is not defined or false == dont_run_homebrew_tasks

    - name: "Copy configs"
      tags: configs
      ansible.builtin.include_role:
        name: cp
      vars:
        cp_entity_source: "{{ item.src }}"
        cp_entity_destination: "{{ item.dest }}"
        cp_entity_name: "{{ item.name }}"
        cp_entity_permissions: "0600"
      loop:
        - {
          name: "Wez terminal config",
          src: "./templates/wezterm.lua.j2",
          dest: "~/.config/wezterm/wezterm.lua"
        }
        - {
          name: "Zsh config",
          src: "./templates/zshrc.sh",
          dest: "~/.zshrc"
        }
