---
- name: "Install the whole environment for the OSX"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install packages
      community.general.homebrew:
        name:
          - ack
          - act
          - ansible
          - ansible-lint
          - bat
          - btop
          - eza
          - fd
          - gron
          - helm
          - htop
          - jq
          - k9s
          - kind
          - ktlint
          - kubectx
          - midnight-commander
          - ncdu
          - pwgen
          - tig
          - watch
          - yamllint
          - yq
          - zellij
          - zsh
          - zsh-history-substring-search
        state: present

    - name: Install casks
      community.general.homebrew_cask:
        state: present
        name:
          - alt-tab
          - wezterm
          - font-fira-code

    - name: "Copy Wez terminal config"
      ansible.builtin.template:
        src: "./templates/wezterm.lua.j2"
        dest: "~/.config/wezterm/wezterm.lua"
        mode: "0600"

    - name: "Copy Zsh config"
      ansible.builtin.template:
        src: "./templates/zshrc.sh"
        dest: "~/.zshrc"
        mode: "0600"
