---
fish_executable: "/usr/local/bin/fish"
fisher_file_path: "{{ user_dir }}/.config/fish/functions/fisher.fish"
starship_file_path: "{{ user_dir }}/.config/fish/conf.d/starship.fish"
user_dir: "/Users/{{ username }}"
