---
ansible_user: miju
ansible_group: staff
ansible_python_interpreter: /usr/local/bin/python3.14
firefox_profile_dir: /Users/miju/Library/Application Support/Firefox/Profiles/pex9ak71.default-release

pi_plannotator_planning_model:
  provider: "openai-codex"
  id: "gpt-5.5"
pi_plannotator_planning_thinking: "xhigh"
pi_plannotator_executing_model:
  provider: "openai-codex"
  id: "gpt-5.5"
pi_plannotator_executing_thinking: "medium"
