---
ansible_user: miju
ansible_group: staff
ansible_python_interpreter: /usr/local/bin/python3.14
firefox_profile_dir: /Users/miju/Library/Application Support/Firefox/Profiles/pex9ak71.default-release

homebrew_packages:
  - ack
  - act
  - anomalyco/tap/opencode
  - ansible
  - ansible-lint
  - bat
  - btop
  - dust
  - eza
  - fd
  - fzf
  - gh
  - gron # Make JSON greppable!
  - helm
  - htop
  - jq
  - k9s
  - kind
  - ktlint
  - kubectx
  - lazygit
  - micro
  - mise
  - MonitorControl
  - ncdu
  - pwgen
  - ripgrep
  - starship
  - television
  - tig
  - watch
  - worktrunk
  - yamllint
  - yq
  - zellij
  - zoxide
  - zsh
  - zsh-history-substring-search
